volumes:
  fastapi-service-data:
      external: true
services:
  fastapi-service:
    build:
      context: ./fastapi-service
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-service:/app
    environment: 
      SIGNING_KEY: b'hsc-ZQUloHWTR5jtvirgWCjozyMTo8WccEDRuQlzfoY='
      DATABASE_URL: postgresql://atarba-user:atarba-password@db/db-atarba
      WAIT_HOSTS: db:5432
      PORT: 8000
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

  db:
    image: postgres:14.7-bullseye
    environment: 
      POSTGRES_PASSWORD: atarba-password
      POSTGRES_USER: atarba-user
      POSTGRES_DB: db-atarba
    ports:
      - "15432:5432"
    volumes:
      - fastapi-service-data:/var/lib/postgresql/data
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
            